version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - docker --version

  build:
    commands:
      - echo Build started on `date`
      - docker build -t my-web-app .

  post_build:
    commands:
      - echo Build completed on `date`
      - docker images

